### ISSUE TITLE
IntersectionObserver

### ISSUE THREAD

**Issue by KenjiBaheux** [w3ctag/spec-reviews#104]
Spec: https://github.com/WICG/IntersectionObserver
Issues: [tracker](https://github.com/WICG/IntersectionObserver/issues/)
Discussion: https://www.w3.org/2015/08/27-positionobserver-irc (+ discussion in the issue tracker)

cc/ @ojanvafai

**Comment by torgo** [comment]
Discussed on call 9-March-2016.

**Comment by torgo** [comment]
TAG consensus is sounds good - would like to review again when going through web platform working group. See minutes of our call for full discussion. Otherwise closing.
