### ISSUE TITLE
Filters in Canvas 2D

### ISSUE THREAD

**Issue by alijuma** [w3ctag/spec-reviews#116]
Spec: https://html.spec.whatwg.org/multipage/scripting.html#filters

We'd like to ship this in Blink in Chrome 52, which in practice means enabling it by May 6th.

Blink Intent-to-Ship: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/Jhwj8QAYaFY
Mozilla Intent to Implement and Ship: https://groups.google.com/forum/#!topic/mozilla.dev.platform/AKVp1cqQYHQ

This spec has been discussed on the whatwg mailing list:
https://lists.w3.org/Archives/Public/public-whatwg-archive/2014Sep/0110.html

cc @mstange @junov

**Comment by dbaron** [comment]
I think this is mostly straightforward, allowing application of existing filter concepts to canvas.  I filed two minor issues (see above).

I don't think this exposes any issues about the atomicity of canvas drawing operations beyond what's already exposed by [<code>globalAlpha</code> and <code>globalCompositeOperation</code>](https://html.spec.whatwg.org/multipage/scripting.html#compositing), although it would be nice to check that somebody else agrees with my assessment there.

One other thing I need to look into a little further is that I recall that SVG filters used to define a concept of a [filter effects region](https://www.w3.org/TR/SVG11/filters.html#FilterEffectsRegion).  I need to figure out if this concept is still present in filters or if it's been removed.  (I think I recall some talk about removing it.)  If it's not removed, then this section would presumably need to define it.  (I think it's better off gone, replaced by "use the region that's needed to get the right result".)

**Comment by dbaron** [comment]
Discused this briefly on the call today.  As noted, I raised the 5 minor issues above, but we don't see a need to have this on the TAG's agenda again, though hopefully there will be continued discussion in the linked issues.
