### ISSUE TITLE
URNbis documents

### ISSUE THREAD

**Issue by mnot** [w3ctag/spec-reviews#117]
The IETF URNBIS WG is finishing up [a number of documents](https://datatracker.ietf.org/wg/urnbis/documents/).

In particular, [this one](https://datatracker.ietf.org/doc/draft-ietf-urnbis-semantics-clarif/) may be of interest to the TAG; it removes URNs from the semantic (but not syntactic) constraints of URIs (and thus URLs).

For example, a URI processor now wouldn't be able to assume that a URN that uses a hierarchical form could be a base for a relative URI, because the semantics there have changed.

**Comment by annevk** [comment]
Wut. That just means that they are a different thing altogether and cannot be put in the same box anymore. `new URL()` will continue to treat URLs starting with `urn:` just the same as before.

**Comment by torgo** [comment]
Picked up at [TAG teleconf 11-may-2016](https://github.com/w3ctag/meetings/blob/gh-pages/2016/telecons/05-11-agenda.md)

**Comment by torgo** [comment]
discussed at telecon https://github.com/w3ctag/meetings/blob/gh-pages/2016/telecons/06-01-agenda.md - agreed to put on hold and discuss at stockholm

**Comment by mnot** [comment]
Updated in Stockholm; it looks like the parts that might have had architectural impact have been walked back (specifically, removing semantics from path and query in URNs). Closing.
