### ISSUE TITLE
relative URLs are not updated pushState()

### ISSUE THREAD

**Issue by plinss** [w3ctag/spec-reviews#118]
In current implementations when a document's URL is updated via pushState() or inserting/modifying a base element, relative URLs are not updated to the new URL. 

See https://lists.w3.org/Archives/Public/www-style/2016Mar/0298.html

**Comment by plinss** [comment]
Discussed at CSS F2F, implementers seem reluctant to fix this due to fears of web compat issues.

**Comment by annevk** [comment]
I don't think there's anything to fix either. What specification would you claim is violated here?

**Comment by plinss** [comment]
Not claiming a specific spec is violated, but that the behavior (or lack thereof) is broken. If elements or CSS with relative URLs are modified after pushState or base change, those relative URLs will be evaluated against the new base, so two elements with the same relative url can have different resolved URLs.

**Comment by slightlyoff** [comment]
We've had requests to change this, specifically inside Shadow DOM contexts, from Google teams (specifically, the AMP team). It seems worth investigating the extent to which we can change it.

**Comment by travisleithead** [comment]
Closing this to track in HTML (https://github.com/w3c/html/issues/545)
