### ISSUE TITLE
Review secure contexts

### ISSUE THREAD

**Issue by torgo** [w3ctag/spec-reviews#124]
Discussed on call 6 July - WebAppSec thinks Secure Contexts is ready for CR, https://w3c.github.io/webappsec-secure-contexts/

**Comment by travisleithead** [comment]
This is looking pretty good from my standpoint. Has feature detection [generally], and makes reference to the [SecureContext] WebIDL extended attribute which has a behavior I'm happy with.

Lots of good examples and descriptions. +1 for transition to CR.

**Comment by torgo** [comment]
me, @mnot @ylafon @triblondon @slightlyoff @hadleybeeman @dbaron @timbl could you register your comments?

**Comment by mikewest** [comment]
Great, thanks Travis, et al. Do y'all still want to publish as a joint document?

/cc @hillbrad @wseltzer

**Comment by mikewest** [comment]
Issued a CfC to transition to CR in https://github.com/w3c/webappsec-secure-contexts/issues/39. If y'all are so thrilled with the doc that you'd still like this to be a joint publication, I'm happy to change the document accordingly.

**Comment by torgo** [comment]
We discussed at [Stockholm f2f](https://github.com/w3ctag/meetings/blob/gh-pages/2016/07-stockholm/agenda.md) gave some feedback and positive support to WebAppSec publishing the document.

**Comment by torgo** [comment]
NB: we may publish a companion finding tbd.
