### ISSUE TITLE
Review window.visualViewport API

### ISSUE THREAD

**Issue by bokand** [w3ctag/spec-reviews#128]
It's cutting it a little close but we wanted to ship this in Chrome M54 which is branching in ~3-4 weeks. I only realized that the intent to ship process requires/suggests a TAG review but the API surface is quite small and simple.

Link: https://github.com/WICG/ViewportAPI
Blink [Intent to Implement](https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/Intent$20to$20implement$20viewport/blink-dev/LqQXLx93mEo/C50y8EiLAQAJ)
Chromestatus [entry](https://www.chromestatus.com/features/5737866978131968)

Thanks.

**Comment by torgo** [comment]
Taking a look at this on our [call today](https://github.com/w3ctag/meetings/blob/gh-pages/2016/telecons/08-10-agenda.md).

**Comment by torgo** [comment]
Hi @bokand  - we discussed / triaged on today's TAG call. Some of this discussion and potential issues raised by @plinss @hadleybeeman and @dbaron are in [the minutes](https://pad.w3ctag.org/p/10-08-2016-minutes.md). We're going to try to write up a more complete review within the next week. In the mean time we can continue discussion in this thread if you have any immediate response to the questions raised in our minutes. Thanks!

**Comment by bokand** [comment]
Thanks! Re: privacy review, I can't think of how it might affect privacy
but I don't have enough experience to really know. FWIW, all these values
can be (roughly) calculated already, albeit with terrible hacks and some UA
checks. You can look at some of the madness in the polyfill
<https://github.com/WICG/ViewportAPI/blob/master/polyfill/visualViewport.js>
at how they can be calculated today (Still trying to make it work in iOS
Safari).

Another thing worth mentioning, this fits in the larger question of
coordinate spaces. Edge/IE moved to the model of having a separate viewport
for layout/visual and tried to make pinch-zoom mostly invisible to the
page. However, for compatibility, they left some properties responsive to
pinch-zoom. Chrome matched Edge's semantics. This leaves us in a position
where getBoundingClientRect and event client coordinates are relative to
the layout viewport while window.scrollX/Y and window.innerWidth/Height
report the values of the visual viewport. This leads to bugs as seen in the
duplicates of crbug.com/489206. In Safari, all these APIs are relative to
the visual viewport.

We tried to remedy the situation in crbug.com/571297, shipping the solution
for a full milestone in M48 which made scrollX/Y and innerWidth/Height
relative to the layout viewport and made pinch-zoom totally invisible to
script. We didn't see any reports of broken content but got significant
developer push back since they could no longer reason about the
pinch-zoomed state without an additional API. We undid that change and it
was part of our motivation for prioritizing this API.

IMO, we'd still like to move in the direction of making pinch-zoom (and
other features affecting the visual viewport, like the on screen keyboard
on some platforms) invisible to the existing API surface. This has the nice
property that these actions don't inadvertently cause the page to change.
e.g. User zooms in to see some item on the page but the script keeps an
overlay plastered to the screen obscuring the intended item. This is
especially useful since most development still takes place on desktop
devices using emulation where these issues don't come up as readily. With
this API, if a page really wants to do something on these actions it has to
be explicit about it. The alternative is to make all the APIs relative to
the visual viewport but this has the down side of being easier to build
surprising/broken UX.

Sorry for the wall-of-text, just wanted to give some background.

Thanks,
David

**Comment by dbaron** [comment]
Is there a URL for viewing the spec without cloning the repo and viewing it locally (or just reading the raw HTML in github's UI)?  (The repo is using a <code>master</code> branch rather than a <code>gh-pages</code> branch, so I can't use a wicg.github.io URL...)

**Comment by ymalik** [comment]
Here is a URL to the draft spec: https://rawgit.com/WICG/ViewportAPI/master/index.html

**Comment by dbaron** [comment]
OK, I read through the spec and filed a bunch of issues (see above).

I think the one other thing I'm concerned about is whether the names of the properties on the VisualViewport interface make sense.  They're certainly a hodgepodge of things from other places in the platform (Element and MouseEvent), although I'm not aware of <code>scale</code> occuring elsewhere as a property (but see Window.devicePixelRatio).  It's not obvious to me that, put together, they really make sense as an API.  Perhaps some diagrams would help.  But on the flip side, it's not clear to me what the relative values of having (1) a sensible API, locally vs. (2) an API whose names share meaning with names elsewhere in the platform are.  On the flip side, it's also not clear to me how solid the analogies are between these properties and the correspondingly-named ones on Element and MouseEvent.

I don't have any suggestions on the topic immediately, but it might be worth a little more discussion.

**Comment by bokand** [comment]
Thanks, the feedback is useful!

Regarding the `scale` attribute. The reason we leaned towards `scale` rather than `zoom` is to match the `<meta name="viewport">` tag. That's really the only place where `pinch-zoom` values are defined so I think matching that is useful.

**Comment by dbaron** [comment]
FWIW, the [current link to the spec](https://rawgit.com/WICG/ViewportAPI/master/spec.html) is now different.

We had a little more discussion in today's TAG meeting about https://github.com/WICG/ViewportAPI/issues/35 and provided a little further feedback there.

I think the TAG is ready to close this review issue, although if it's possible to make further improvements on the naming we'd be happy to see that, or even to provide further feedback if needed.
