### ISSUE TITLE
Disable Local Playback During Audio Sharing

### ISSUE THREAD

**Issue by chenqiang1986** [w3ctag/spec-reviews#137]
We want to add a constraint googDisableLocalEcho in the audio part of getUserMedia call.
It only works with audio capturing (either from the whole system or a tab).
If set googDisableLocalEcho:true, then we are going to mute the local playback of the audio being shared.

For example, if one wants to share a tab, and specifies 
getUserMedia({video:..., audio:{mandatory:{sourceId:<some id>, googDisableLocalEcho:true}}})
Then during the sharing of the tab, the tab is muted on the sender's side. Otherwise the shared tab is still playing out on the sender's side.

**Comment by dbaron** [comment]
Do you have a link to a specification and explainer for this?

Is "goog" a google vendor prefix?  Why should this API have such a prefix?

**Comment by alvestrand** [comment]
This would live better as a bug against the Media Capture and Streams spec. Asking for TAG review for a modification of an open WG's spec is .... kind of unusual, I think.

**Comment by chenqiang1986** [comment]
Wrong place. Thanks.
