### ISSUE TITLE
WebRTC

### ISSUE THREAD

**Issue by plinss** [w3ctag/spec-reviews#14]
General feedback to the WebRTC working group; feedback on the rechartering process.

**Comment by mnot** [comment]
Discussed in NYC; Dan still coordinating.

**Comment by torgo** [comment]
Discussed at April 2015 f2f - mostly considering rechartering - Dan to report back at next telco

**Comment by mnot** [comment]
Discussed in SF; still didn't work talking to Fluffy. 

Hmm.

Had general discussion of re-charter. @torgo to report back.

**Comment by timbl** [comment]
This issue is a bit vague -- what about WebRTC?  Charter? Technology? Privacy?

**Comment by travisleithead** [comment]
Related WebRTC issue. https://github.com/w3c/webrtc-pc/issues/179

**Comment by torgo** [comment]
Current topics of discussion at Berlin F2F  are: WebRTC rechartering and privacy issues.

**Comment by chaals** [comment]
Proposed charter: http://www.w3.org/2015/06/webrtc-charter.html

**Comment by torgo** [comment]
If parties are using WebRTC technology to aid fingerprinting and not in service of actual services delivered over WebRTC then maybe this is an indication that an additional permission step should be required.

**Comment by torgo** [comment]
One threat model discussed: in the use of e.g. Tor browser or VPNs by activists who may want to conceal their source IP, WebRTC may enable attackers to determine those IP addresses.

**Comment by diracdeltas** [comment]
relevant: https://tools.ietf.org/html/draft-ietf-rtcweb-security-arch-11#section-5.4

**Comment by diracdeltas** [comment]
Tor disables webrtc at FF compilation time currently but are thinking of re-enabling it with IP address hiding: https://trac.torproject.org/projects/tor/ticket/16221 (really interesting idea to use hidden services for ICE!)

**Comment by torgo** [comment]
Agreed today: Mark will report back on the privacy issue. We have no substantive feedback on the rechartering.

**Comment by torgo** [comment]
Picked up at Boston f2f.

**Comment by torgo** [comment]
https://wiki.mozilla.org/Media/WebRTC/Privacy

**Comment by torgo** [comment]
http://www.w3.org/2015/09/09-webrtc-minutes.html#item06

**Comment by torgo** [comment]
https://www.w3.org/2011/04/webrtc/wiki/images/d/da/WebRTC_IP_Address_Privacy.pdf

**Comment by torgo** [comment]
@mnot to provide a summary on the next call.

**Comment by plinss** [comment]
Discussed 2015-09-23 telcon follow up at TPAC

**Comment by triblondon** [comment]
Demo of local IP address discovery: https://diafygi.github.io/webrtc-ips/

**Comment by triblondon** [comment]
Potential positive use cases include stuff like https://www.sharedrop.io/

**Comment by torgo** [comment]
Discussed at Melbourne f2f: https://github.com/w3ctag/meetings/blob/gh-pages/2016/01-mel/agenda.md

**Comment by mnot** [comment]
Will continue to revisit this issue and get updates from WebRTC to assess potential privacy impact.

**Comment by mnot** [comment]
Some data:
  https://freedom-to-tinker.com/blog/englehardt/the-web-privacy-problem-is-a-transparency-problem-introducing-the-openwpm-measurement-tool/
  
> A preliminary analysis [5] of a 50,000 site pilot measurement from October 2015 suggests that WebRTC local IP discovery is used on the homepages of over 100 sites, from over 20 distinct scripts.

Chrome mitigation pref:   https://chromium.googlesource.com/chromium/src/+/7c98bab02128ae9fdc4fcc9a9df38588af86290e%5E!/chrome/common/pref_names.cc

Firefox discussion:
  https://groups.google.com/forum/#!topic/mozilla.dev.media/L6Rx9ubSjMc

**Comment by torgo** [comment]
Ref: https://github.com/w3c/webrtc-pc/issues/179 it looks like they have closed this issue. @dontcallmedom can you elaborate here and explain how the issue was resolved so that we can close this issue off please?

**Comment by dontcallmedom** [comment]
The [RTCWeb IP Handling draft](https://tools.ietf.org/html/draft-ietf-rtcweb-ip-handling-01) describe the strategies that browsers are invited to adopt to avoid revealing sensitive IP addresses.

Essentially:
* by default, only "safe" IP addresses get exposed; this includes so called "private" IP addresses (e.g. `192.168.0.1`) since in practice they don't reveal much, but not hidden-by-VPN IP addresses
* once camera/mic access has been granted, more IP addresses get exposed to find more network efficient paths
* browsers should provide a mechanism to never reveal any other IP address than the public one

**Comment by mnot** [comment]
Discussed at IETF 95; minutes [here](https://www.ietf.org/proceedings/95/minutes/minutes-95-rtcweb) (search for "IP-address handling").

**Comment by slightlyoff** [comment]
Do we need to follow up at all here?

**Comment by mnot** [comment]
We can get someone (EKR or MT) to come in and update us in Stockholm on Thursday, if wanted. I'll need a heads up to ask them soon, though.

**Comment by torgo** [comment]
EKR presented at the [Stockholm f2f](https://github.com/w3ctag/meetings/blob/gh-pages/2016/03-london/agenda.md).
