### ISSUE TITLE
Review OffscreenCanvas

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/spec-reviews#144]
Implementation proceeding in Mozilla and Chromium. We should take a look at this. 

The PR into HTML: https://github.com/whatwg/html/pull/1876
WHATWG Wiki entry: https://wiki.whatwg.org/wiki/OffscreenCanvas
Chrome Status entry: https://www.chromestatus.com/feature/5424182347169792

**Comment by slightlyoff** [comment]
The draft review of WebVR mentions this: https://github.com/w3ctag/spec-reviews/blob/master/2016/11/webvr.md

**Comment by dbaron** [comment]
Some review has already occurred in #141.

**Comment by dbaron** [comment]
Closing in favor of #141.
