### ISSUE TITLE
Remote Playback API

### ISSUE THREAD

**Issue by tidoust** [w3ctag/spec-reviews#145]
Hello TAG!

I'm requesting a TAG review of:

  - Name: Remote Playback API
  - Specification URL: https://w3c.github.io/remote-playback/
  - Explainer, Requirements Doc, or Example code: See [Use cases and Requirements](https://github.com/w3c/remote-playback/blob/gh-pages/use-cases.md) document, and note the [Introduction](https://w3c.github.io/remote-playback/#introduction) and [Examples](https://w3c.github.io/remote-playback/#examples) sections in the spec.
  - Primary contacts: @avayvod, @mounirlamouri, @tidoust, @anssiko

Further details (optional):

  - Relevant time constraints or deadlines: by end of 2016. The group intends to finalize the API beginning of 2017 and transition to CR then.
  - [ ] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The Second Screen WG will run that evaluation in parallel. The spec does not contain a Privacy and Security section yet.
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/). I had not noticed this document before. The Remote Playback API seems to follow these principles.

The Remote Playback API is to media content what the Presentation API is to web content. Although the API is different (the Remote Playback API extends the `HTMLMediaElement` interface), the spec re-uses patterns and design consideration from the Presentation API whenever appropriate.

Work on the API is not over yet. The Second Screen WG does not anticipate major changes to the API surface though and believes now is a good time to gather wide review on the document. [Known issues](https://github.com/w3c/remote-playback/issues) so far are considered minor, expect [issue #41](https://github.com/w3c/remote-playback/issues/41) which discusses the set of media playback features that remote playback devices must support and the impact of remoting playback on the observable behavior from the controlling page's perspective. The group welcomes feedback from the TAG on this issue. Let us know if you'd like us to go deeper into details.

For background, we mentioned the Remote Playback API (the spec did not have a name at the time) when we requested a TAG review of the Presentation API. The [resulting TAG review](https://github.com/w3ctag/spec-reviews/blob/master/2015/presentation-api.md) contains some thoughts on "Presenting the content of an `<audio>` or `<video>` element" in particular.

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our [Github repo](https://github.com/w3c/remote-playback/) for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @notify [github usernames]

(any of these options is fine in practice)

**Comment by tidoust** [comment]
FYI, initial security and privacy evaluation now done in https://github.com/w3c/remote-playback/issues/67
The latest Editor's draft contains a [Security and privacy section](https://w3c.github.io/remote-playback/#security-and-privacy-considerations) as well.

**Comment by cynthia** [comment]
Apologies for the delay, I'll be taking this on. Who in the group has time to have a chat about this? @avayvod, @mounirlamouri, @tidoust, @anssiko ?

**Comment by anssiko** [comment]
The editors @avayvod (UTC-05:00) and @mounirlamouri (UTC+00:00) are on the critical path with regard to answering detailed technical questions that may arise. They are also able to give an update on the implementation status as needed. I'm happy to join as well in the chair capacity (UTC+02:00).

The group does not hold frequent teleconferences, but we can organize a topic specific call for disseminating TAG feedback if that'd be deemed helpful.

**Comment by cynthia** [comment]
A formal call isn't necessarily needed for now, just had a couple casual questions on the landscape of work doing in second screen (and somewhat related specs) to catch up on this - a informal chat on IRC to catch up on the backlog would be enough to prevent unnecessary nitpicking from me.

**Comment by cynthia** [comment]
In general LGTM, the one outstanding issue as been opened as w3c/remote-playback#74 .

**Comment by torgo** [comment]
Discussed and agreed on [today's f2f](https://github.com/w3ctag/meetings/blob/gh-pages/2017/telcons/04-18-agenda.md).
