### ISSUE TITLE
KeyBoardEvent 'code' and 'key' spec reviews wanted

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/spec-reviews#155]
Hello TAG,

The WebPlat WG would welcome your review of these two specs:

1. UI Events KeyboardEvents Code Values:
https://w3c.github.io/uievents-code/

2. UI Events KeyboardEvents Key Values:
https://w3c.github.io/uievents-key/

We're just preparing to move into CR. With apologies for the short notice, we'd really appreciate your comments before 10th April if possible.

Comments are preferred on Github, but if you could ping me an email to let me know when you're done it'll help me keep the paperwork straight.

1. UI Events KeyboardEvents Code Values:
https://github.com/w3c/uievents-code/

2. UI Events KeyboardEvents Key Values:
https://github.com/w3c/uievents-key/

Thanks
Léonie
--
@LeonieWatson tink.uk Carpe diem

**Comment by travisleithead** [comment]
Setting milestone before the requested deadline of April 10th.

**Comment by travisleithead** [comment]
Reviewed the KeyboardEvent.key spec--and it looks great.

Reviewed the KeyboardEvent.code spec. It's also fantastic. 
* Noted one linking issue in [Section 3](https://w3c.github.io/uievents-code/#code-value-tables), with the text `=KeyboardEvent.code=` that looks like it was supposed to be a link.
* Looks like some political problems with https://w3c.github.io/uievents-code/#key-alphanumeric-functional (i.e., `AltRight`) :-) but I guess we can let that slide.

**Comment by torgo** [comment]
Agreed to close issue on today's call.
