### ISSUE TITLE
Custom Elements

### ISSUE THREAD

**Issue by ylafon** [w3ctag/spec-reviews#16]
LC As of http://www.w3.org/TR/2013/WD-custom-elements-20131024/
Edcopy: https://dvcs.w3.org/hg/webcomponents/raw-file/tip/spec/custom/index.html

**Comment by mnot** [comment]
Discussed in NYC; dominic following up.

**Comment by domenic** [comment]
Found the bug, was filed already https://www.w3.org/Bugs/Public/show_bug.cgi?id=24579 and has recently come up again on public-webapps.
