### ISSUE TITLE
Performance Observer Review (formerly Navigation Timing 2 concepts)

### ISSUE THREAD

**Issue by domenic** [w3ctag/spec-reviews#18]
https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/NavigationTiming2/Overview.html

At first glance `getEntriesByType` seems ... weird.

**Comment by mnot** [comment]
Discussed in NYC; alex to review.

**Comment by torgo** [comment]
Question: does the group want our feedback? We need to reach out and schedule a discussion with them on a future telcon.

**Comment by igrigorik** [comment]
@torgo re, feedback: yes. FWIW, we're doing a lot of shuffling and spec cleanup work at the moment, so (a) make sure you're looking at the latest draft, and (b) check the open issues as we have a bunch of work in flight.

**Comment by torgo** [comment]
Discussed on call 5-Aug – we want to be involved when they need us but we need to be able to respond to a concrete request for feedback. Issue to be reassigned to Boston f2f.

**Comment by torgo** [comment]
Picked up in Boston.

**Comment by torgo** [comment]
@slightlyoff : "strange that it's not possible to query the navigation timing api with reference to a resource."

**Comment by dbaron** [comment]
Editor's draft is now at https://w3c.github.io/navigation-timing/

**Comment by torgo** [comment]
@slightlyoff to write up some comments in advance of a joint discussion. We could discuss with @igrigorik at TPAC or beforehand if it can be arranged.

**Comment by slightlyoff** [comment]
Per the TPAC discussion, I need to update the draft review to also discuss the Performance Observer API designs that are coming down the pike.

**Comment by travisleithead** [comment]
Need to check-in with current status of Performance Observer spec and implementation progress. Should revisit at next TAG f2f meeting.

**Comment by igrigorik** [comment]
- Firefox has it implemented behind a flag: https://bugzilla.mozilla.org/show_bug.cgi?id=1165796
- Chrome has it implemented behind a flag: https://plus.google.com/+IlyaGrigorik/posts/c4xiQ9fxCpf
- Edge lists is as "under consideration": https://dev.windows.com/en-us/microsoft-edge/platform/status/performanceobserver

Can we prioritize this? Are there are any particular questions we can address to resolve this?

**Comment by toddreifsteck** [comment]
@igrigorik What subset of performance timeline features have Firefox and Chrome implemented on Performance Observer? (Nav Timing/Resource Timing/User Timing/Frame Timing/Server Timing/other?)

Are all open spec issues from TPAC 2015 on when a Nav Timing is delivered to the Performance Observer resolved?

**Comment by igrigorik** [comment]
As far as I can tell, [Mozilla's implementation](https://bugzilla.mozilla.org/show_bug.cgi?id=1165796) is feature complete (including new getEntries filtering) and integration with all the shipped perf APIs (user, nav, and resource timing). 

The implementation in Chrome enables PerfObserver interface and integrates with User + Resource Timing. Nav Timing support is missing because we need to update our NT implementation to v2 -- once that's done the observer support will be there.

**Comment by slightlyoff** [comment]
Apologies for the delay in getting back to everyone. Overall [Performance Timeline 2](https://www.w3.org/TR/performance-timeline-2/) looks good!

A few things stand out (some of them are editorial, sorry!):

 - It'd be great for there to be a separate explainer doc that goes into more detail about the problems that NT2 solves and the sample code you might write to use it to address those issues. 
 - In section 3, step 3.1, where is `new entry` allocated?
 - In step 3, are you _really_ meaning to get the list of registered performance observer objects from the global environment? Could it be a more standard data structure like a list or map hidden away using a symbol?
 - The "low priority queue" language is interesting...are there other specs that use similar priority statements that you're aware of?
 - Where is the list of types that you can listen for via a PerformanceObserver listed? E.g., `frame` seems to relate to [Frame Timing](https://www.w3.org/TR/frame-timing/), but I'm not sure what's definitive.
 - Can Performance Observers be used to observe page load that may have already happened? How does that work?

Thanks!

**Comment by igrigorik** [comment]
Thanks for the review Alex!

> It'd be great for there to be a separate explainer doc that goes into more detail about the problems that NT2 solves and the sample code you might write to use it to address those issues.

I assume you meant Perf Timeline 2, not Nav Timing 2. 

I think we can address this in the intro section. We already provide a PerfObserver code sample and I think we can just: (a) clarify that this is a v2 feature, (b) explain why it should be a preferred way to access the timeline. 

> In section 3, step 3.1, where is new entry allocated?

That algorithm defines the steps that are invoked by other specifications when they need to queue a "new entry" - e.g. [Frame Timing allocates new entry and invokes the algorithm](http://w3c.github.io/frame-timing/#processing).

> In step 3, are you really meaning to get the list of registered performance observer objects from the global environment? Could it be a more standard data structure like a list or map hidden away using a symbol?

What would that symbol be associated with? 

- We started with "unit of related similar-origin browsing contexts's" - [same as MutationObserver](https://www.w3.org/TR/dom/#mutation-observers).
- Boris and Anne [suggested that we should be using "global environment"](https://github.com/w3c/performance-timeline/issues/44#issuecomment-140911703) - [commit](https://github.com/w3c/performance-timeline/pull/47/commits/457000f2f1447a9b9ae7a814212e26d659387e9b).

> The "low priority queue" language is interesting...are there other specs that use similar priority statements that you're aware of?

I think IntersectionObserver is attempting to do something similar by leveraging requestIdleCallback - [open bug to cleanup interop](https://github.com/WICG/IntersectionObserver/issues/108). PerfObserver came about before we had rIC. It might make sense to go back and define PerfObserver to fire via rIC. 

> Where is the list of types that you can listen for via a PerformanceObserver listed? E.g., frame seems to relate to Frame Timing, but I'm not sure what's definitive.

There is a note in 3.1 that lists all valid entryType values, with links to each spec: https://www.w3.org/TR/performance-timeline-2/#the-performanceentry-interface

> Can Performance Observers be used to observe page load that may have already happened? How does that work?

No. If you register an observer after an event has already happened, you won't get a notification for it. If you want to get notifications for resource timing / nav timing entries when the page is loading, you should register the PerfObserver as a first thing in your doc -- e.g. inline the registration snippet in the head of the doc, before any resource declarations.

**Comment by torgo** [comment]
Taken up on 20-07-2016. We agreed to close the issue.
