### ISSUE TITLE
CSS Font Loading

### ISSUE THREAD

**Issue by domenic** [w3ctag/spec-reviews#20]
http://dev.w3.org/csswg/css-font-loading/

Interesting stuff, including SetClass.

**Comment by mnot** [comment]
Discussed in NYC; @domenic looking into it.

**Comment by mnot** [comment]
Discussed in SF; @torgo to follow up with @domenic and Kenji B.

**Comment by domenic** [comment]
I finally went back and looked through the old concerns about this. (Had to dig through my old email account in fact.) They have all since been taken care of.

**Comment by torgo** [comment]
Thanks, Domenic – any further info you ca point us to on that (just for closure)?

**Comment by domenic** [comment]
The original concern (from Ryan Sleevi) was about the initialization process for FontFace objects being underspecified and buggy in a few areas. These concerns were addressed over time in the following commits:

- https://github.com/w3c/csswg-drafts/commit/88134a76d2b039f2ca99942e7e76ec83fb33392a
- https://github.com/w3c/csswg-drafts/commit/b9923152182a54ccaf16330149049631af30912e
- https://github.com/w3c/csswg-drafts/commit/069a1bb6aa6bda56596989c9c805e9f6e0f5ea51
- https://github.com/w3c/csswg-drafts/commit/425954e5a71e19ef8de9504c869c0df71e54589e
- https://github.com/w3c/csswg-drafts/commit/ba0a889ba69fe9c29de20a15eb975b67769e9151
- https://github.com/w3c/csswg-drafts/commit/408a81a942e7e5aa18f461a50ed2495a3f62ced0
- https://github.com/w3c/csswg-drafts/commit/9bbfc20b4a4b5e3698e1d713b1ee46b2d31c7cd1

**Comment by torgo** [comment]
You rock.

**Comment by tabatkins** [comment]
Alternately: I do.
