### ISSUE TITLE
Web NFC API

### ISSUE THREAD

**Issue by domenic** [w3ctag/spec-reviews#22]
http://www.w3.org/2012/nfc/web-api/

**Comment by mnot** [comment]
Discussed at NYC; @torgo to e-mail chair and discuss context, implementer state, etc.

**Comment by torgo** [comment]
Have emailed chairs will report back and potentially schedule for a future call based on feedback.

**Comment by mnot** [comment]
Discussed at SF; @torgo to follow up.

**Comment by anssiko** [comment]
The latest Web NFC spec to be reviewed is at http://w3c.github.io/web-nfc/

I suggest you update the initial comment to clear any confusion.

Since this issue was opened, this spec work has been moved from WG (http://www.w3.org/2012/nfc/) to CG (https://www.w3.org/community/web-nfc/) to attract wider participation and to cater specifically for browser vendors. The CG participants now include Google and Mozilla, among others. The spec has been redesigned to address implementers' concerns and is now targeted at browsers (cf. the old spec in the WG had a dependency on the now obsoleted SysApps' security model).

I'm the chair of the newly created Web NFC CG. Please let me know if you have any questions.

**Comment by torgo** [comment]
Questions raised at f2f: can a webapp be invoked as a result of a NFC interaction?

**Comment by torgo** [comment]
Looks like for user-initiated actions this is OK. What other use cases could be taken into account such as the physical web use cases? These bring up the registration problem.

**Comment by torgo** [comment]
@slightlyoff : API design looks good and is "modern"

**Comment by torgo** [comment]
Question: should we have a focused discussion on NFC on a future call where we bring the spec authors and others from relevant groups / implementations together? Would this help to accelerate the work?

**Comment by torgo** [comment]
Agreed at f2f: @torgo to discuss with @anssiko and see how we can help push this forward.

**Comment by anssiko** [comment]
Bringing the spec editors @zolkis and @kenchris in the loop.

The API design seems to be digestible based on initial feedback. That said, we're aware of the [open issues][1] in GH, notably @annevk's feedback on the use of [URL objects][2]. Any TAG guidance on this specific issue would be helpful.

To accelerate the work and iron out the rough edges, the group believes a good next step is to gather further implementation feedback. To that end, @riju and @alexshalamov are working on an experimental Chromium implementation that we hope will further inform the specification. We should be able to send an intent to implement out this week.

[1]: https://github.com/w3c/web-nfc/issues
[2]: https://github.com/w3c/web-nfc/issues/26

**Comment by anssiko** [comment]
The [Intent to Implement in Chrome][1] is out. It includes more information on the implementation approach, platforms initially supported etc. Please chime in on [blink-dev][2] with your feedback.

[1]: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/dIbUdDU9a6E
[2]: https://groups.google.com/a/chromium.org/forum/#!forum/blink-dev

**Comment by torgo** [comment]
Taken up at Boston f2f. @travisleithead will review the actual API https://w3c.github.io/web-nfc/ and report back with a draft appraisal and will present back to TAG on 7-oct.

**Comment by torgo** [comment]
Discussing [our feedback](https://github.com/w3ctag/spec-reviews/blob/master/2015/10/nfc-feedback.md) at TPAC WebBluetooth discussion.

**Comment by travisleithead** [comment]
With the review complete, and (of course) leaving the door open for addition issues and followup, unless you object @anssiko, I'd like to close this review issue.

**Comment by anssiko** [comment]
Thank you for the review @travisleithead, please close this issue.

**Comment by travisleithead** [comment]
Super!
