### ISSUE TITLE
Navigation Error Logging

### ISSUE THREAD

**Issue by domenic** [w3ctag/spec-reviews#24]
https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/NavigationErrorLogging/Overview.html

Needs promises

**Comment by domenic** [comment]
Reviewed! Via email to their list. http://lists.w3.org/Archives/Public/public-web-perf/2015Jan/0014.html

Maybe we should add a link to that to this repo...

**Comment by mnot** [comment]
Discussed in NYC; @domenic to re-review. Will probably close after that.

**Comment by domenic** [comment]
New draft is much simpler and uses a HTTP header instead of a JS API. Looks pretty good to me: https://cdn.rawgit.com/w3c/navigation-error-logging/new/index.html

However I'll note that in the past @slightlyoff has agitated for an API for CSP and this seems to be moving in the opposite direction, so maybe he has opinions?

**Comment by mnot** [comment]
Discussed in SF; @slightlyoff concerned about persistence aspect and privacy considerations. We agree that this seems like a "powerful" feature.

We'd also like to see an API. @slightlyoff to write up a review.

**Comment by igrigorik** [comment]
@mnot @slightlyoff for context, discussion on why JS API was removed: https://lists.w3.org/Archives/Public/public-web-perf/2015Jan/0023.html

**Comment by slightlyoff** [comment]
I think the logic there makes sense. Has any thought been given to if/when SWs interact with reports?

**Comment by igrigorik** [comment]
@slightlyoff good question, we have not. Opened a bug: https://github.com/w3c/network-error-logging/issues/54#issuecomment-105597935

**Comment by torgo** [comment]
Discussed on call 5-aug. Might not be anything to comment on any more. @slightlyoff thinks we can close the issue.
