### ISSUE TITLE
WebRTC Identity Provider Selection

### ISSUE THREAD

**Issue by domenic** [w3ctag/spec-reviews#28]
Via @annevk:

http://dev.w3.org/2011/webrtc/editor/webrtc.html#identity-provider-selection

[Mozilla intent to implement](https://groups.google.com/d/msg/mozilla.dev.platform/QiF18J4vccA/rDclGYmFPBEJ)

The API design doesn't make sense to me, and perhaps we could help with that, but I think that's a lesser concern next to the idea of an entirely new identity primitive. This is worth us all understanding and making sure it fits well with the rest of the platform.

I need to do a lot of reading to really get this. The Mozilla intent to implement gives a nice one-paragraph overview, but the entire WebRTC world is pretty far outside my area of expertise. Any help would be welcome.

**Comment by domenic** [comment]
Opened https://github.com/w3c/webrtc-pc/issues/172 to get the ball rolling.

**Comment by mnot** [comment]
Discussed in NYC; issue has been raised.
