### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by domenic** [w3ctag/spec-reviews#34]
Larry Masinter in IETF would appreciate our feedback

**Comment by mnot** [comment]
Discussed in NYC; ongoing, no driver yet, but we'll get there.

**Comment by mnot** [comment]
Discussed  in SF; overtaken by events, as is in RFC Editor queue. 

http://www.ietf.org/proceedings/88/slides/slides-88-appsawg-8.pdf
http://datatracker.ietf.org/doc/draft-ietf-appsawg-multipart-form-data/
