### ISSUE TITLE
CSS Regions

### ISSUE THREAD

**Issue by plinss** [w3ctag/spec-reviews#35]
http://dev.w3.org/csswg/css-regions-1/

Editors are specifically asking for TAG review and guidance

**Comment by mnot** [comment]
Discussed in NYC; no status available.

**Comment by twirl** [comment]
I incorporated feedback into initial draft, see https://github.com/w3ctag/spec-reviews/pull/44

**Comment by slightlyoff** [comment]
Per F2F discussion with @astearns at today's TAG meeting, I think we can close this issue with the following disposition:

 - The TAG is glad to see a Box Tree API anticipated in the design of the current API
 - We're also glad to see so much thought put into the fragmenting aspects and are anxious to see more API develop around the [CSS Fragmentation draft](http://www.w3.org/TR/css3-break/)
 - The emergence of Houdini APIs for text/line breaking are encouraging
 - We'd like to see the CSS Working Group outline how layout timing work with regards to the overflow events
 - More example code would be appreciated.

In general, we're happy with the state of the spec and will encourage other groups to work to help explain how Regions work and integrate/iterate collaboratively with that spec.
