### ISSUE TITLE
CSP

### ISSUE THREAD

**Issue by domenic** [w3ctag/spec-reviews#42]
https://w3c.github.io/webappsec/specs/CSP2/

@slightlyoff has thoughts on a reflective API

**Comment by mnot** [comment]
Discussed in SF; @slightlyoff TBD.

**Comment by torgo** [comment]
Discussed at Berlin f2f: Alex: Webappsec in process of formalizing CSP level 2 (renamed from 1.1). We should reengage once they have CSP 2 out the door.

**Comment by mikewest** [comment]
Current plan is to republish http://www.w3.org/TR/CSP2/ as a CR to deal with something we had to remove, then proceed to PR and eventually REC.

I plan to kick off CSP3 (again) this quarter. Hope that actually happens.

**Comment by domenic** [comment]
Edited OP to point to new CSP2 URL

**Comment by torgo** [comment]
Discussed at Boston f2f : https://pad.w3ctag.org/p/09-15-2015-minutes

**Comment by torgo** [comment]
CSP Issues list here: https://github.com/w3c/webappsec/milestones/CSP%203

**Comment by travisleithead** [comment]
@mnot prepare thoughts around improving release speed and/or modularity of CSP3 for a TPAC discussion.

**Comment by mikewest** [comment]
I am curious about these ideas, and would like to hear more. :)

**Comment by mnot** [comment]
@mikewest - People are just noticing that the monolithic nature of CSP releases is in some ways hurting adoption; people (wrongly or rightly) feel they need to implement the entire version, and users feel they have to understand the entire new spec before using it.

Getting new features onto a release train can be frustrating too (e.g., `cookie-scope`)

Also, giving a new major version number to it when it contains compatible changes confuses many.

No concrete suggestions, but one straw-man would be to make the major versions of CSP only come out when there's a breaking change, and to allow other specs to define extensions.

**Comment by mnot** [comment]
@mikewest - another CSP issue worth talking about again is the delivery mechanism. When I look at sites like Twitter, who have really long CSP headers:
  https://redbot.org/?uri=https%3A%2F%2Ftwitter.com%2Fmnot&req_hdr=User-Agent%3AMozilla%2F5.0+%28X11%3B+U%3B+Linux+x86_64%3B+en-US%29+Gecko+Firefox%2F3.0.8

... it makes me think we can do better (especially considering that this will consume most of the compression context in HTTP/2 -- 4k -- meaning it'll make header compression really inefficient). 

I've been noodling on a mechanism to allow a site to put its policies in a .well-known location and then refer to them by a token in responses when the client indicates it's fetched that location; would you care to look at a straw-spec?

**Comment by mikewest** [comment]
@mnot, @travisleithead, @hillbrad: I've been thinking about a modular CSP myself, actually. I do think it's a good idea ("CSP Core" + smaller specs), though I'm not entirely sure where the lines are. For instance, I started on https://w3c.github.io/webappsec/specs/csp-cookies/ this afternoon to chat about (and because it's ~2 years late). Is that enough to stand on its own? I don't know. UPGRADE was, but it was significantly more complex. *shrug* Let's talk about it at TPAC, I guess?

@mnot: 1. Twitter's policy _is_ huge. 2. I have a pinning proposal I haven't touched in ~6 months (https://w3c.github.io/webappsec/specs/csp-pinning/), and some of the discussion pointed in the direction of a manifest. Maybe HTTP/2 push solves the latency problems associated with a blocking request that I've always pushed back on in the WG? I'd be interested in the strawspec (but would prefer discussing it in an issue on w3c/webappsec if possible. :)

**Comment by travisleithead** [comment]
I took a quick look at https://w3c.github.io/webappsec/specs/csp-cookies/ and while it is small, I am drawn to smaller, easier-to-digest documents. So IMO, this smaller-spec works well.

The risk, as you note, is finding the right place to draw the lines that decreases the interdependencies between the docs. I'd have to spend more time understanding the larger CSP doc to have an intuition on whether the current divide is good. Ultimately though, you probably know best :)

**Comment by mnot** [comment]
+1 here as well -- seems like an encouraging direction, but like travis says, will require some careful oversight.

**Comment by mikewest** [comment]
Oversight... oversight... If only I could find some group that concerns itself with architectural technologisms to provide some adult supervision while we work through that discussion. :)

**Comment by mnot** [comment]
I meant oversight by people who actually know about CSP :)

**Comment by mnot** [comment]
@mikewest - I don't see how CSP Pinning helps, because a server doesn't know when it's safe to omit CSP headers for any give request. 

Anyway, I owe you a straw-man proposal, I think...

**Comment by mikewest** [comment]
Hello, lovely TAGians. https://w3c.github.io/webappsec-csp/ is far enough along that I'd appreciate some feeback from y'all about the integration points between CSP, HTML, and Fetch, as well as the hooks I've built in for extensibility. Happy to chat with anyone who's interested, on a call or via email/GitHub/whatever. :)

**Comment by torgo** [comment]
Thanks, @mikewest. I've put it on the agenda for [this week's call](https://github.com/w3ctag/meetings/blob/gh-pages/2015/telcons/12-09-agenda.md) and hopefully we can get you some useful feedback soon.

**Comment by mnot** [comment]
Discussed briefly at Melbourne; will still review.

**Comment by mnot** [comment]
Hey Mike,

Overall this looks like a reasonable evolution for CSP; switching to fetch seems very sane.

The extensibility also looks reasonable. It's good to see that there are multiple implementations of the full level 2 spec (at least according to caniuse; is that correct?); it'd be even better to see Firefox get up to speed...

I'm still concerned about the overall size of CSP headers, as well as its uptake by sites. I think there may be a *much* bigger discussion of what our stance to securing the Web should be lurking in that latter point, but that shouldn't hold this up.

One nit - You need to update the IANA registry entries for all of the affected directives in the IANA Considerations section.

**Comment by torgo** [comment]
discussed in telecon 1 june 2016 https://github.com/w3ctag/meetings/blob/gh-pages/2016/telecons/06-01-agenda.md

**Comment by mnot** [comment]
@mikewest we've discussed that and the TAG likes the direction you're going in; we don't have any substantial architectural comment, beyond saying that CSP 3 looks like a good evolution, modularity looks about right, and using Fetch is sane.
