### ISSUE TITLE
Credential Management API

### ISSUE THREAD

**Issue by mikewest** [w3ctag/spec-reviews#49]
Hello, illustrious TAG members! Would you mind spending a few minutes skimming https://w3c.github.io/webappsec/specs/credentialmanagement/ and jotting down your thoughts?

Thanks!

**Comment by mikewest** [comment]
Note: @slightlyoff and @domenic provided (very) early feedback on the spec, but I've fiddled with it a lot since then. I suspect I've made mistakes since then. :)

**Comment by domenic** [comment]
(Former TAG member here.) I filed a bunch of issues on minor things to the bug tracker.

Overall quite excited with what this brings. A clear incremental improvement, with good future potential but also solid wins in the present.

**Comment by mikewest** [comment]
Thanks, Domenic. I appreciate the time you spent going through the document and filing issues. I might even address some of them today!

**Comment by torgo** [comment]
Closed on [telecon 20-May-2015](https://github.com/w3ctag/meetings/blob/gh-pages/2015/telcons/05-06-upgrade-insecure-agenda.md).

**Comment by mikewest** [comment]
This spec has changed a bit since May, and I'm gearing up to start convincing people that it's worth shipping. Would requesting a lightweight re-review be appropriate? 

https://w3c.github.io/webappsec/specs/credentialmanagement/

/cc @torgo @mnot @slightlyoff

**Comment by mikewest** [comment]
(Also, skimming the notes, it seems like there were some open questions y'all wanted to get back to.)

**Comment by torgo** [comment]
reopened discussion based on @mikewest's request at f2f in Boston.

**Comment by torgo** [comment]
@travisleithead indicated that he will review and provide feedback.

**Comment by travisleithead** [comment]
Given FIDO's recent submission to W3C, I need to revisit this. May need to wait a few weeks though...

**Comment by mikewest** [comment]
http://www.w3.org/Submission/2015/SUBM-fido-web-api-20151120/ is the submission, for clarity.

Happy to chat if it would help you get context from my side. I talked with Vijay and Israel about earlier versions of the FIDO API that coincided a bit more clearly with the credentials API. I'm not sure what happened that pulled the draft they submitted away from that model. Getting them to line up a little more clearly would be great.

**Comment by travisleithead** [comment]
I'm going to need more time to think about how this relates to FIDO (and to review it on its own merit). I'm currently still brushing up on FIDO for our Melbourne F2F. Should be in a better position to look at this after that meeting.

**Comment by slightlyoff** [comment]
I guess what I'd love to see is a sketch of example code that uses Credential Management with FIDO to accomplish something useful. Seems like it's not premature now that we have a FIDO submission.

**Comment by travisleithead** [comment]
Note, recent discussion on blink-dev's intent to ship: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/7ouLjWzcjb0

**Comment by travisleithead** [comment]
Latest FIDO (Now Web Authentication): https://w3c.github.io/webauthn/
Credential Management L1: https://w3c.github.io/webappsec-credential-management/

Previous questions (from [20 May 2015 teleconference](https://github.com/w3ctag/meetings/blob/gh-pages/2015/telcons/05-20-credentials%26fingerprinting-minutes.md))
* security of the name (`idName`) attribute when reading after transferring to alternate origin (mnot)
   * This appears to be addressed in that `SiteBoundCredential::name` and `SiteBoundCredential::iconURL` are both `readonly` now. Other related security and privacy considerations are outlined in: https://w3c.github.io/webappsec-credential-management/#security-cross-origin-leakage, and this seems complete (as expected from Mike West).

Relationship and alignment of `Credential` between Web Authentication and Credential Management.
* WebAuthn doesn't seem to [take any dependency ](https://w3c.github.io/webauthn/#dependencies)on Credential Management
    * Uses a generic (but matching) description of `interface Credential`. The type is `"ScopedCred"` (case-mismatch with other types defined in Credential management: `"password"`, `"federated"`
    * There are some weird mis-matches between Credential management's `SiteBoundCredential` and Web Authentication's [`ScopedCredentialInfo`](https://w3c.github.io/webauthn/#scopedcredentialinfo). However, they look to be roughly compatible, though I expect Web Authentication may need to refactor a bit for the two specs to align better. (e.g., I recommend that Web Authentication sub-class the `SiteBoundCredential`. It's unclear why Web Authentication would want to leverage the Credential Management storage system (vs. just IndexedDB), since their ScopedCredentialInfo objects (and the Credential they contain) are primarily used during registration (to be sent back to the server), or optionally to help in UI selection assistance during later getAssertion() calls--but is not really even needed then (getAssertion, on success, returns the asserted credential needed to send back to the server).

Other notes:
* User agents MAY use the Public Suffix List to offer/share (with user mediation) Credentials from the TLD to an eTLD+1 for example. Leaves it up to the user agent within a security framework.

**Comment by torgo** [comment]
discussed [8-june-2016](https://github.com/w3ctag/meetings/blob/gh-pages/2016/telecons/06-08-agenda.md) - and agreed to close - further discussion to #97 .
