### ISSUE TITLE
Upgrade Insecure Requests

### ISSUE THREAD

**Issue by mikewest** [w3ctag/spec-reviews#50]
Hello, lovely TAG members. Would you mind reading over https://w3c.github.io/webappsec/specs/upgrade/ in your copious free time, and providing some feedback to the WG?

We're shipping an initial cut at this in Chrome 43, so I expect implementation experience to help shape the near-term future of the feature. It would be excellent to get your take on the broader problem of migration to HTTPS to see what else we could be doing to address it.

**Comment by diracdeltas** [comment]
This has been a recurring subject in the last 2 days of TAG meetings; I'll try to provide feedback today.

**Comment by diracdeltas** [comment]
I took a shot at this in #54; check it out mike!

**Comment by diracdeltas** [comment]
Closed by #54
