### ISSUE TITLE
contributing.md document needed for tag reviews

### ISSUE THREAD

**Issue by torgo** [w3ctag/spec-reviews#53]
Document the following:

* timeliness of required review
* has a security review been done?
* expectation of what happens next

**Comment by dbaron** [comment]
We have https://github.com/w3ctag/spec-reviews/blob/master/README.md but it doesn't seem to answer the above questions.

**Comment by torgo** [comment]
Edited the document to include those questions. Will continue to edit that doc. In the mean time, let's close this.
