### ISSUE TITLE
Media Capture and Streams

### ISSUE THREAD

**Issue by dontcallmedom** [w3ctag/spec-reviews#57]
Media Capture and Streams is in Last Call review period, and the TAG was among the [groups flagged to bring a review](https://lists.w3.org/Archives/Member/chairs/2015AprJun/0017.html):
> Technical Architecture Group, for an overall review of the API, 
especially the introduction of the concept of a IANA registry-based 
constraints system, the use of promises, and our handling of persistent 
permissions

The last call period ends on May 15.

**Comment by torgo** [comment]
@travisleithead "use of promises looks fine to me."

**Comment by travisleithead** [comment]
@slightlyoff: asks how this relates to Streams regarding who's buffering (if at all) and when. There may be an inconsistency between the two models. Specifically, this came up in regards to the MediaStream.clone() API.

@mnot notes that the per-origin uniqueness aspect of deviceID isn't clearly speced in the normative section of the document (it's mentioned in the privacy considerations though).

**Comment by slightlyoff** [comment]
Specifically, I think we need to chat with @domenic about the consumption model and the implicit semantics that come from having a `.clone()` method.

Similarly, I think we should talk to @cwilso et. al. about `AudioContext::createMediaStreamSource()` and how these streams get from bytes to decoded bytes. How the heck does that happen? Where does decode take place? On what thread? Can I have access to those decoders from script too?

**Comment by dontcallmedom** [comment]
I assume this input will be built into a more formal feedback to the WebRTC and DAP groups? If so, any idea of when that feedback might be available? Thanks!

**Comment by diracdeltas** [comment]
@travisleithead could you make sure the review incorporates or addresses https://github.com/w3c/mediacapture-main/issues/212?

**Comment by torgo** [comment]
Taken up at Boston f2f. Looks like issue 212 was taken on board.

**Comment by torgo** [comment]
@travisleithead : @dontcallmedom still waiting on feedback on use of streams, relation of media streams to Streams cap-s. Are we happy with the media streams spec?

**Comment by torgo** [comment]
@dontcallmedom can you join us on the tag telecon 10-7 possibly to close this off?

**Comment by dontcallmedom** [comment]
is it at 8pm UTC on Oct 7? I can probably make it, yes

**Comment by travisleithead** [comment]
I think we discussed this already and had no further comments, but forgot to close this. I'm closing it now--if I'm in error, please re-open.
