### ISSUE TITLE
Review Payments Working Group Charter

### ISSUE THREAD

**Issue by torgo** [w3ctag/spec-reviews#67]
https://lists.w3.org/Archives/Public/public-new-work/2015Aug/0001.html

**Comment by plinss** [comment]
Alex will send invites for sept f2f

**Comment by torgo** [comment]
Can we request some additional technical info on on deliverables and relationships including eg. architectural diagram? (discussed at Boston f2f)

**Comment by torgo** [comment]
Mark to revise his comments to incorporate the above.
