### ISSUE TITLE
Media TF discussion

### ISSUE THREAD

**Issue by slightlyoff** [w3ctag/spec-reviews#69]
Per today's TAG meeting, there's appetite from @ddorwin to discuss issues around secure stop and key re-issuance at an upcoming call.

Leaving untagged for folks to agree to schedule, but tentatively Sept 2nd call.

/cc @plinss @torgo

**Comment by plinss** [comment]
Set sept-02 milestone for planning purposes

**Comment by torgo** [comment]
Replaced by issue 73.
