### ISSUE TITLE
Secure / Powerful / Features / Contexts

### ISSUE THREAD

**Issue by torgo** [w3ctag/spec-reviews#75]
@mikewest has indicated at the Boston f2f that he believes the document is ready for wider review. @diracdeltas says looks good. We need to provide some more feedback as a group.

https://w3c.github.io/webappsec/specs/powerfulfeatures/

**Comment by torgo** [comment]
Tag consensus is that publishing as a normative document (in webappsec) would be a good idea.

**Comment by dbaron** [comment]
Status of spec discussed at Melbourne face-to-face, morning of January 14.

**Comment by dbaron** [comment]
Sounds like we're happy with things based on that discussion, so ready to close this issue.

(See minutes for details.)
