### ISSUE TITLE
Security Questionnaire

### ISSUE THREAD

**Issue by torgo** [w3ctag/spec-reviews#77]
We need to complete and publish the security questionnaire as a note.

https://github.com/w3ctag/security-questionnaire/issues/6

**Comment by torgo** [comment]
Picked up telcon 25-November-2015

**Comment by ylafon** [comment]
Was published on dec 10th.

**Comment by mnot** [comment]
Discussed at Melbourne F2F; @mnot to drive (following up with mike west)

**Comment by mnot** [comment]
Discussed with Mike; will revisit in ~six months to see how it's being used.

**Comment by mnot** [comment]
This presentation at HRPC in IETF Berlin may be useful to think about, esp. last slide:
  https://www.ietf.org/proceedings/96/slides/slides-96-hrpc-2.pdf

**Comment by mnot** [comment]
https://www.ietf.org/proceedings/96/slides/slides-96-hrpc-2.pdf

**Comment by mnot** [comment]
Grist for the mill / for consideration:
  https://lists.w3.org/Archives/Public/public-payments-wg/2016Jul/att-0013/WebpaymentsAPISecurityandPrivacyChecklist.pdf

**Comment by hadleybeeman** [comment]
Closed at TAG f2f in Boston: https://pad.w3ctag.org/p/2017-02-08-minutes.md
