### ISSUE TITLE
Create a "advice for spec authors" page

### ISSUE THREAD

**Issue by torgo** [w3ctag/spec-reviews#78]
Do we need a special "advice for spec authors" page that calls out current best practice for spec authors (e.g. the security and privacy checklist, promises guide, etc...)?

**Comment by domenic** [comment]
https://w3ctag.github.io/design-principles/ could morph into this or we could leave that more narrowly focused on API surface and link to it from this

**Comment by torgo** [comment]
I think the design principles doc would be top of the list on this page but I see the page as more of a list of links - some of which might be to TAG or other w3c docs and some of which might be to other best practice stuff...

**Comment by mnot** [comment]
I've started keeping state at:
  https://github.com/w3ctag/wiki/wiki/TAG-Guidance-for-Spec-Authors

Please add links, etc. and then we'll fill out some prose around them.

**Comment by mnot** [comment]
I think this can be closed; we're keeping this currently at <http://w3ctag.github.io/workmode/>
