### ISSUE TITLE
HTTP Opportunistic Security

### ISSUE THREAD

**Issue by mnot** [w3ctag/spec-reviews#80]
https://github.com/httpwg/http-extensions#http-opportunistic-security

Discussed in Boston; @mnot to follow up, try to coordinate discussion with IETF, browser security folk.

**Comment by dbaron** [comment]
Discussed at Melbourne face-to-face on Thursday Jan 14 (see minutes); concluded TAG doesn't need to do anything else for this, so can close issue.
