### ISSUE TITLE
Automotive Working Group - API Refactor or Not?

### ISSUE THREAD

**Issue by paulboyes** [w3ctag/spec-reviews#81]
The Automotive Working Group has an ongoing discussion regarding a potential refactor of [Vehicle Information Access API](http://rawgit.com/w3c/automotive/master/vehicle_data/vehicle_spec.html) and [Vehicle Data Spec](http://rawgit.com/w3c/automotive/master/vehicle_data/data_spec.html) and would greatly appreciate a review/weighing in of the [issue](https://github.com/w3c/automotive/issues/37) by TAG. 

The key issue is whether to generalize the methods identifying the piece of data that is being accessed as a parameter or having member interfaces concretely defined to avoid "magic strings".  I believe the group has settled on the latter with some nuance.

Having an objective review from TAG would be much appreciated.  Again the [issue](https://github.com/w3c/automotive/issues/37) is here ['https://github.com/w3c/automotive/issues/37'](https://github.com/w3c/automotive/issues/37).  

Do not hesitate to let us know if you have any questions or need clarification.

Thanks,

Paul J. Boyes, Co-Chair

**Comment by dbaron** [comment]
Does @domenic's API design document say something about things like this?

**Comment by paulboyes** [comment]
@dbaron Where can one find @domenic's API design doc?

**Comment by peterMelco** [comment]
Is there a definition of a "magic string" ? I think that using strings as parameters to select certain data and return that is not magic in any sense ?

**Comment by paulboyes** [comment]
@peterMelco "magic string" means something like "data is simply a String, the name of the data point like 'vehicleSpeed' "  This would be like a string/key instead of a predefined member.   

@tripzero right Kevron?

**Comment by tripzero** [comment]
Right.  "Magic strings" refers to attributes referenced by a string instead
of by a concrete object: vehicle.speed vs vehicle.get("speed")

**Comment by dbaron** [comment]
API design doc is http://w3ctag.github.io/design-principles/

**Comment by torgo** [comment]
Hi @travisleithead I've put this on the agenda for tomorrow as it was assigned to this week's milestone.

**Comment by torgo** [comment]
Punted until next week's call.

**Comment by paulboyes** [comment]
This was initially around issue 37.  Now there is the added issue 72 (https://github.com/w3c/automotive/issues/72).  Your input on that would be much appreciated as well.

Thanks!

**Comment by travisleithead** [comment]
Discussed in our TAG call today ([raw minutes](https://pad.w3ctag.org/p/03-02-2016-minutes.md)). We had some followup clarifications, and are looking to have someone from the Automotive group join us in a future call.

**Comment by travisleithead** [comment]
We had a [great call today](https://pad.w3ctag.org/p/10-02-2016-minutes.md). From the sound of things, the group may be taking the spec in a new direction (moving away from a Web API, and more toward a REST-ful model, perhaps making use of Web Sockets. We are closing this issue now, and will be happy to be notified of a new spec review issue request when the Automotive specs have been updated. Thanks!

**Comment by marcoscaceres** [comment]
Is there any minutes from the call?

**Comment by bkardell** [comment]
@marcoscaceres the link @travisleithead shared above looks like minutes?
