### ISSUE TITLE
Geofencing FPWD

### ISSUE THREAD

**Issue by torgo** [w3ctag/spec-reviews#89]
https://w3c.github.io/geofencing-api/

**Comment by torgo** [comment]
Built on service worker ++

**Comment by torgo** [comment]
taken up 11-11

**Comment by torgo** [comment]
Agreed to schedule time at the next f2f.

**Comment by dbaron** [comment]
https://lists.w3.org/Archives/Public/www-tag/2016Jan/0008.html

**Comment by hadleybeeman** [comment]
We checked in on this at the [London f2f](https://github.com/w3ctag/meetings/blob/gh-pages/2016/03-london/agenda.md) — looks like they haven't had time to make progress on it. Will check again at next TAG f2f.

**Comment by hadleybeeman** [comment]
Still true. (As above.)

**Comment by torgo** [comment]
Agreed to close due to it being obsolete in our f2f 8 feb 2017.
