### ISSUE TITLE
Bluetooth API Security Model

### ISSUE THREAD

**Issue by torgo** [w3ctag/spec-reviews#90]
Some question came up in the Bluetooth API discussion at - given that a pairing permission is granted by the user on an origin basis (device to origin) should this be allowed when the request is made from an iFrame or only when the origin is visible to the user? Example: I grant skype.com to have access to my bluetooth speaker but then if I'm on Outlook.com and Outlook.com embeds a Skype.com iframe, should that have that be able to use my speaker?

**Comment by torgo** [comment]
Separate question potentially around physical web security model. Suggested use case: a physical web device advertises a URL and you select that URL and the web page can then use the bluetooth API to connect to that device.

**Comment by torgo** [comment]
Taken up 11-11 telcon
@slightlyoff : Patterns they can look at security "options for iframes"...  CSP directives - usage indicators which could be recommended (per UA decision).

**Comment by torgo** [comment]
@slightlyoff: could we highlight some useful patterns?

**Comment by slightlyoff** [comment]
I think there's a couple of things we can contribute. At a first pass, it seems out of scope to make a hard-and-fast decision about _if_ this should be enabled for sub-documents, but perhaps _how_ this can be enabled. Options include the `sandbox` attribute for iframes: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

Adding an option and denying by default might be reasonable. An open question for us in the TAG is the extent to which we should try to recommend a pattern for new powerful features as they relate to iframes. Consistency here seems desirable (and like it's on us to figure out).

Separately, I think we should discuss with @mikewest and the WebAppSec gang how we might think about a similar process for getting new features flagged for control by CSP.

**Comment by torgo** [comment]
We discussed this somewhat in our brief conversation with EKR at [Stockholm f2f](https://github.com/w3ctag/meetings/blob/gh-pages/2016/07-stockholm/agenda.md) (day 1).

**Comment by slightlyoff** [comment]
Security considerations section has been fleshed out significantly since the last time we looked at this: https://webbluetoothcg.github.io/web-bluetooth/use-cases.html#security_privacy

We still don't have a uniform way of handling iframe delegation of control, but this seems like something we don't need to solve in this issue. Closing.

**Comment by marcoscaceres** [comment]
Can you provide a summary of what Ekr said?
