### ISSUE TITLE
HTTP 451 Status

### ISSUE THREAD

**Issue by jorabin** [w3ctag/spec-reviews#99]
Recent approval of the HTTP Status code 451 [1] has led to (wide) discussion of its purpose of indicating censorship (e.g. [2]). A Twitter exchange between myself and @mnot clarifies that it's intended also for copyright purposes such as DMCA. Following an email exchange between myself and @torgo, he requests that I raise this for TAG consideration:

As well as being intended to indicate censorship (which is what it's being popularly described as) it's also intended for e.g. copyright abuse, which is a) much less clear from its popular description and b) anything from far less sinister to a force for good.

I am concerned that as a responsible operator of a Web site my use of this status in support of my and other's rights to their content could easily be misunderstood. It would be useful to me, at least, for there to be some explanatory use cases. 

As a trivial example, as an origin server, I may choose to offer the pictures on my site only when they are served in the context of my own Web pages and not when they are referenced by other sites. If I see, from the "Referer" HTTP header or by other means that another site is including my image, is 451 an appropriate response, given that my permission (i.e. my license) to use the image does not include that use? This obviously applies both to my own pictures, whose rights I own and other people's pictures that I have a license to use for my blog only.

[1] https://datatracker.ietf.org/doc/draft-ietf-httpbis-legally-restricted-status/

[2] http://www.wired.co.uk/news/archive/2015-12/21/error-451-internet-censorship-alert

**Comment by mnot** [comment]
Discussed on the 7 January 2016 call. This status code is still new, and we expect that the community might develop best practices and possibly even related HTTP extensions (e.g., headers) over time. 

We'd encourage you to engage with that community if you have questions about its use; a good starting point would be the HTTP Working Group. https://httpwg.github.io/
